use sha2::{Sha256, Digest};
use crate::errors::CloakResult;

/// A cryptographic challenge for a Storage Provider
pub struct Challenge {
    pub shard_hash: String,
    pub nonce: String,
    pub offset: usize,
    pub length: usize,
}

/// The proof generated by the Storage Provider
pub struct Proof {
    pub shard_hash: String,
    pub nonce: String,
    pub proof_hash: String,
}

/// Generates a Proof of Storage by hashing a specific byte range of a shard with a random nonce.
pub fn generate_proof(shard_data: &[u8], challenge: &Challenge) -> CloakResult<Proof> {
    if challenge.offset + challenge.length > shard_data.len() {
        return Err(crate::errors::CloakError::Protocol("Challenge out of bounds".into()));
    }

    let chunk = &shard_data[challenge.offset..challenge.offset + challenge.length];
    
    // Hash = SHA256(Nonce + Chunk)
    let mut hasher = Sha256::new();
    hasher.update(challenge.nonce.as_bytes());
    hasher.update(chunk);
    let proof_hash = hex::encode(hasher.finalize());

    Ok(Proof {
        shard_hash: challenge.shard_hash.clone(),
        nonce: challenge.nonce.clone(),
        proof_hash,
    })
}

/// Verifies a Proof of Storage. In a real network, the challenger doesn't have the full shard,
/// so verification is usually done via a pre-computed Merkle Tree root. 
/// For our integration, we mock the verification assuming the challenger has the Merkle root.
pub fn verify_proof(proof: &Proof, expected_hash: &str) -> bool {
    proof.proof_hash == expected_hash
}
